[package]
name = "smzdh"
version = "0.1.0"
authors = ["paomian <qtang@leancloud.rocks>"]

[dependencies]
hyper = "0.9"
router = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
websocket = "0.17.0"
postgres = "0.11"
log = "*"
lazy_static = "0.1.*"
iron = "*"
redis = "0.5.3"

[dependencies.log4rs]
version = "*"
features = ["yaml"]
