[package]
name = "smzdh_commons"
version = "0.1.0"
authors = ["paomian <xpaomian@gmail.com>"]

[dependencies]
iron = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
rust-crypto = "*"
rustc-serialize = "*"
postgres = "*"
redis = "*"
log = "*"
rand = "*"
router = "*"
