refresh_rate: 30
appenders:
  stdout:
    kind: file
    path: "log/requests.log"
    encoder:
    pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
loggers:
  app::backend::db:
    level: info
  app::requests:
    level: info
    appenders:
      - stdout
    additive: false
